version: "3.4"
services:
    webserver:
        image: nginx:1.13-alpine
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:8080"

    app:
        build:
            context: .
            dockerfile: docker/node/Dockerfile
            args:
                www_data_uid: 1000
                www_data_gid: 1000
        working_dir: /home/www-data/app
        volumes:
            - .:/home/www-data/app
        command: tail -F anything
